"""add certifications

Revision ID: 02b4aa5c0881
Revises: b42b3fda4564
Create Date: 2020-12-17 13:51:29.622744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b4aa5c0881'
down_revision = 'b42b3fda4564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('certification_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('row_order', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('certification_id')
    )
    op.create_index(op.f('ix_certifications_name'), 'certifications', ['name'], unique=False)
    op.create_index(op.f('ix_certifications_row_order'), 'certifications', ['row_order'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certifications_row_order'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_name'), table_name='certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
