"""inspectors table

Revision ID: 0a9fd3a454a6
Revises: 38c0f801e3de
Create Date: 2020-11-29 18:59:06.655671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a9fd3a454a6'
down_revision = '38c0f801e3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspectors',
    sa.Column('inspector_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('login_type', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('inspector_id')
    )
    op.create_index(op.f('ix_inspectors_email'), 'inspectors', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspectors_email'), table_name='inspectors')
    op.drop_table('inspectors')
    # ### end Alembic commands ###
