"""adding fields to inspector user table

Revision ID: 16982b5f1b89
Revises: f524b51033a0
Create Date: 2020-11-29 19:34:20.313118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16982b5f1b89'
down_revision = 'f524b51033a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspectors', sa.Column('language_code', sa.String(), nullable=True))
    op.add_column('inspectors', sa.Column('phone_no', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspectors', 'phone_no')
    op.drop_column('inspectors', 'language_code')
    # ### end Alembic commands ###
