"""certifications and parent_organizations with relationship

Revision ID: 31faaa960fd6
Revises: 02b4aa5c0881
Create Date: 2020-12-23 02:39:41.344292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31faaa960fd6'
down_revision = '02b4aa5c0881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parent_organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('certifications', sa.Column('parent_organization_id', sa.Integer(), nullable=True))
    op.add_column('certifications', sa.Column('short_name', sa.String(), nullable=True))
    op.add_column('certifications', sa.Column('url', sa.String(), nullable=True))
    op.create_foreign_key(None, 'certifications', 'parent_organizations', ['parent_organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_column('certifications', 'url')
    op.drop_column('certifications', 'short_name')
    op.drop_column('certifications', 'parent_organization_id')
    op.drop_table('parent_organizations')
    # ### end Alembic commands ###
