"""adding fails to login table

Revision ID: 38c0f801e3de
Revises: f22a798bf935
Create Date: 2020-11-29 18:23:17.558596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38c0f801e3de'
down_revision = 'f22a798bf935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_login_history', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users_login_history', sa.Column('result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_login_history', 'result')
    op.drop_column('users_login_history', 'email')
    # ### end Alembic commands ###
