"""inspectors logins table w api keys

Revision ID: 3b46576f0f87
Revises: 0a9fd3a454a6
Create Date: 2020-11-29 19:01:42.730079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b46576f0f87'
down_revision = '0a9fd3a454a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
