"""adding phone country

Revision ID: 671b3aa8b09a
Revises: 16982b5f1b89
Create Date: 2020-11-30 10:08:01.483882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671b3aa8b09a'
down_revision = '16982b5f1b89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inspectors', sa.Column('phone_country', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inspectors', 'phone_country')
    # ### end Alembic commands ###
