"""add location_name to facilities table

Revision ID: b2a6d7dd6535
Revises: bb7de0b960ca
Create Date: 2021-01-22 00:55:21.194250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a6d7dd6535'
down_revision = 'bb7de0b960ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facilities', sa.Column('location_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facilities', 'location_name')
    # ### end Alembic commands ###
