"""test

Revision ID: b42b3fda4564
Revises: 6dd1d78a98d0
Create Date: 2020-12-15 10:46:18.268497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42b3fda4564'
down_revision = '6dd1d78a98d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
