"""add bids table

Revision ID: bb7de0b960ca
Revises: 440d0855bb22
Create Date: 2021-01-21 05:53:30.321921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7de0b960ca'
down_revision = '440d0855bb22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bids',
    sa.Column('bid_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.job_id'], ),
    sa.PrimaryKeyConstraint('bid_id')
    )
    op.drop_index('idx_facilities_location', table_name='facilities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_facilities_location', 'facilities', ['location'], unique=False)
    op.drop_table('bids')
    # ### end Alembic commands ###
