"""adding users login hist

Revision ID: f22a798bf935
Revises: 39e9aa83fb7e
Create Date: 2020-09-11 09:24:04.725362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22a798bf935'
down_revision = '39e9aa83fb7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_login_history',
    sa.Column('user_login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('login_type', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('token_id', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_login_id')
    )
    op.create_index(op.f('ix_users_login_history_platform'), 'users_login_history', ['platform'], unique=False)
    op.create_index(op.f('ix_users_login_history_token_id'), 'users_login_history', ['token_id'], unique=False)
    op.create_index(op.f('ix_users_login_history_user_id'), 'users_login_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login_history_user_id'), table_name='users_login_history')
    op.drop_index(op.f('ix_users_login_history_token_id'), table_name='users_login_history')
    op.drop_index(op.f('ix_users_login_history_platform'), table_name='users_login_history')
    op.drop_table('users_login_history')
    # ### end Alembic commands ###
