"""inspectors logins table w api keys

Revision ID: f524b51033a0
Revises: 3b46576f0f87
Create Date: 2020-11-29 19:02:08.345314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f524b51033a0'
down_revision = '3b46576f0f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspector_logins',
    sa.Column('login_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_ip_address', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('login_id')
    )
    op.create_index(op.f('ix_inspector_logins_api_key'), 'inspector_logins', ['api_key'], unique=False)
    op.create_index(op.f('ix_inspector_logins_disabled_at'), 'inspector_logins', ['disabled_at'], unique=False)
    op.create_index(op.f('ix_inspector_logins_inspector_id'), 'inspector_logins', ['inspector_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inspector_logins_inspector_id'), table_name='inspector_logins')
    op.drop_index(op.f('ix_inspector_logins_disabled_at'), table_name='inspector_logins')
    op.drop_index(op.f('ix_inspector_logins_api_key'), table_name='inspector_logins')
    op.drop_table('inspector_logins')
    # ### end Alembic commands ###
